export default [
  {
    key: '1',
    image: 'https://picsum.photos/60/60?random=10.jpg',
    title: 'Frontend Developer (Remote)',
    enterprise: 'Crossover for Work',
    city: 'São Paulo, BR',
    timeAgo: '1 day ago',
    applications: 23,
  },
  {
    key: '2',
    image: 'https://picsum.photos/60/60?random=11.jpg',
    title: 'Desenvolvedor (a) .Net Pleno',
    enterprise: 'Atum Technologies',
    city: 'São Paulo, BR',
    timeAgo: '3 days ago',
    applications: 11,
  },
  {
    key: '3',
    image: 'https://picsum.photos/60/60?random=12.jpg',
    title: 'Desenvolvedor Back-end / Sênior',
    enterprise: 'Pay',
    city: 'Franca, SP',
    timeAgo: '1 week ago',
    applications: 12,
  },
  {
    key: '4',
    image: 'https://picsum.photos/60/60?random=13.jpg',
    title: 'Desenvolvedor .Net',
    enterprise: 'Meet Consulting',
    city: 'São Paulo, BR',
    timeAgo: '3 days ago',
    applications: 15,
  },
  {
    key: '5',
    image: 'https://picsum.photos/60/60?random=14.jpg',
    title: 'Desenvolvedor PHP',
    enterprise: 'Auto',
    city: 'Brasil',
    timeAgo: '3 days ago',
    applications: 0,
  },
];
